/* Generated by pack_sounds.py - do not edit.
 *
 * Regenerate with ./pack_sounds.py after changing sounds.yaml or anything in
 * wav/. Committed alongside sfx_bank.bin so the build never depends on Python.
 */
#pragma once

#include <stdint.h>

#define SFX_BANK_MAGIC        "OSFX"
#define SFX_BANK_VERSION      1
#define SFX_BANK_HEADER_SIZE  16
#define SFX_BANK_ENTRY_SIZE   8
#define SFX_BANK_SAMPLE_RATE  44100

typedef enum {
    SFX_CONNECTED            = 0,   /* wav/connected.wav */
    SFX_GOODKUSH             = 1,   /* wav/goodkush.wav */
    SFX_ON                   = 2,   /* wav/on.wav */
    SFX_STARTUP              = 3,   /* wav/startup.wav */
    SFX_TRAPAHOLICS          = 4,   /* wav/trapaholics.wav */
    SFX_COUNT = 5
} sfx_id_t;
